### ISSUE TITLE
Errors in loading state_dict for RawGAT_ST

### ISSUE THREAD

**Issue by idiein1984** [eurecom-asp/RawGAT-ST-antispoofing#2]
Hi. When I tried to load pretrained model 'Pre_trained_models/RawGAT_ST_mul/Best_epoch.pth',
I got those errors
![1637291355](https://user-images.githubusercontent.com/25583572/142558835-a514d701-7273-4350-a115-878a0c762c16.png)

**Comment by TakHemlata** [comment]
Hi,
Actually, I modified the variable names for git repo (more readable) and the pre-trained model was with the usual variables name such as GAT_layer1 for spectral GAT and that I modified to GAT_layer_spectral in git clean code that's why you are getting this error.

There are many ways to store weights in the new state_dict and then used them. Anyways I update the git repo to old code which I used for the pre-trained model. 

Let me know if need further help.

Thanks
